version: "2"
services:
  SYMFONY_NOTA_BENE:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nota_bene_database
      MYSQL_USER: nota_bene_user
      MYSQL_PASSWORD: unmotdepasse
